### ISSUE TITLE
Support foreign architectures with qemu-debootstrap or mmdebstrap

### ISSUE THREAD

**Issue by jscott0** [lkhq/debspawn#23]
Hi,

If you're not familiar with QEMU user mode, it's like magic! It's a Wine-like wrapper that lets you run foreign executables. It can be used to run foreign chroots, although the statically linked version (`qemu-user-static` package) is needed so it won't have to resolve symbols outside the container.

This works with systemd-nspawn, as I used to do it by hand. The qemu-user-static package comes with a very minimal debootstrap wrapper that takes care of the voodoo, and can probably be used drop-in.

Please add support for it, or for otherwise allowing one to specify an alternative debootstrap executable.

**Comment by ximion** [comment]
This sounds indeed great, and like something worth adding - I do not know though when I will have time for this (honestly, this may take a while), so, patches welcome! ;-)
