### ISSUE TITLE
adduser no longer in Debian base

### ISSUE THREAD

**Issue by hlieberman** [lkhq/debspawn#31]
Transferred from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1024090

> debspawn create unstable fails because it cannot create the builder
user: adduser does no longer seem to be part of the default install.
Either add adduser in include_pkgs in osbase.py, or create the user with
the lower-level tools.

**Comment by ximion** [comment]
This one is already fixed in master, just needs a release (we now use `useradd`)
