### ISSUE TITLE
Use alternate directory for $HOME besides /nonexistent

### ISSUE THREAD

**Issue by hlieberman** [lkhq/debspawn#32]
Transferred from BTS https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1024091

> The builder user is created with /nonexistent as the home directory, and
somewhere between the call to dsrun build-prepare and dsrun build-run
one of the calls to systemd-nspawn -u builder creates the home directory
of the user.
>
> This is bad because this disables the security effect of having an
account's home directory point to a nonexistent directory, and also
because adduser's autopkgtests fail in such an environment since
adduser's autopkgtests test whether the special-case of /nonexistent
(which adduser takes care to never create) is handled correctly.

**Comment by hlieberman** [comment]
It would also be useful if you know whether it's systemd-nspawn or systemd-run that's doing this, so I can tag the correct Debian maintainer to fix it.

**Comment by ximion** [comment]
So far I unfortunately haven't been able to reproduce this - the directory was never created for me...
I've added a workaround to just ensure the directory is deleted, but of course that doesn't fix the root cause which we should still find...

**Comment by ximion** [comment]
So, `systemd-nspawn` really wants to make sure that the user's home directory exists :-/
It also looks like my workaround does not work properly in all circumstances. I will implement a new one that should be more reliable.
