### ISSUE TITLE
Failed to mount /etc/localtime during configure step on debian/sid

### ISSUE THREAD

**Issue by abbbi** [lkhq/debspawn#36]
hi,

the current ongoing usr-is-merge situation broke my existing debian/sid chroots on bookworm. I attempted to update debootstrap to the version in sid and apparently, if creating a new unstable chroot using debspawn, this error is to be
seen during configuration step:

`Failed to mount /etc/localtime (type n/a) on /var/tmp/debspawn/6mqxcr8d/usr/share/zoneinfo/UTC (MS_BIND ""): No such file or directory`

this seems to become an issue, as /etc/localtime ends up beeing a regular file within the created chroot and installing
any package that depends on tzdata fails.

So i setup a debian/sid vm and it seems this issue appears with debspawn in debian/sid, too.
Its reproducible via:

debspawn git checkout + change for:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1055065

```
debspawn --version
0.6.3
debspawn create unstable
┌───────────────────┐
│  Configure        │
└───────────────────┘
Failed to mount /etc/localtime (type n/a) on /var/tmp/debspawn/8levserq/usr/share/zoneinfo/UTC (MS_BIND ""): No such file or directory
Hit:1 http://deb.debian.org/debian unstable InRelease
[..]
debspawn run unstable apt install tzdata
[..]
mv: cannot move '/etc/localtime.dpkg-new' to '/etc/localtime': Device or resource busy
dpkg: error processing package tzdata (--configure):
 installed tzdata package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 tzdata
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

```
(venv) root@sid:~/debspawn# dpkg -l systemd-container
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version      Architecture Description
+++-=================-============-============-=================================
ii  systemd-container 254.5-1      amd64        systemd container/nspawn tools
```

as represented during login: 

```
 debspawn login unstable
[..]
Spawning container debian12.localdomain-unstable-buildd-amd64-jsie on /var/tmp/debspawn/er0w107r.
Press Ctrl-] three times within 1s to kill container.
root@sid:/srv# ls -alh /etc/localtime
-rw-r--r-- 1 root root 2.8K Aug  9 14:10 /etc/localtime
```

using debootstrap to create a regular sid chroot, the file is a symlink:

```
debootstrap sid sid
[..]
ls -alh sid/etc/localtime 
lrwxrwxrwx 1 root root 27 Nov  2 12:02 sid/etc/localtime -> /usr/share/zoneinfo/Etc/UTC
```

and spawning this chroot via systemd-nspawn directly:

```
root@debian12:~# systemd-nspawn -D sid
Spawning container sid on /root/sid.
Press Ctrl-] three times within 1s to kill container.
root@sid:~# ls -alh /etc/localtime 
lrwxrwxrwx 1 root root 41 Nov  2 12:04 /etc/localtime -> ../usr/share/zoneinfo/America/Los_Angeles
```

as for the created image:

```
/var/lib/debspawn/images# mkdir foo; tar -xvf unstable-buildd-amd64.tar.zst -C foo
ls -alh foo/etc/localtime 
-rw-r--r-- 1 root root 2.8K Aug  9 14:10 foo/etc/localtime
```

not quite sure what debspawn does differently in regards to plain systemd-nspawn.

**Comment by ximion** [comment]
I can't seem to reproduce this at all - was the issue maybe solved meanwhile? Can you check again?

**Comment by abbbi** [comment]
> I can't seem to reproduce this at all - was the issue maybe solved meanwhile? Can you check again?

yes, it seems to work now (again) as of today. im unable to reproduce the issue with the debspawn/debootstrap versions in bookworm.

**Comment by ximion** [comment]
Nice, thank you for confirming! There was a phase of weirdness in the archive for sure, but things got resolved very quickly :-)

**Comment by ximion** [comment]
Seconds after making a release, I ran into this...
Nspawn shouldn't behave like this, but at least there's a convenient override that we can apply :-)
