### ISSUE TITLE
Container creation fails with debootstrap >= 1.0.133

### ISSUE THREAD

**Issue by hlieberman** [lkhq/debspawn#37]
The newer versions of debootstrap no longer install packages which are Priority: required but not essential for the buildd variant.  This means that passwd will not be installed, and thus, user creation will fail.

This is tracked downstream as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1055065.

There are a couple of different ways that I could see us fixing this, all with their pros and cons.

### Manually install passwd

This is the simplest option.  We could simply unconditionally pass `--include=passwd` to the invocation of debootstrap.  That would leave us in the exact situation we were in before hand.  However, this means that we are 1) tracking independently what packages are needed, and 2) putting packages into the container that are _technically_ not necessary for the actual build.

### Create the user from outside the container

This is what sbuild does -- it invokes useradd from the host system, not from inside the chroot.  This requires more coding work -- it can't live in `dsrun` -- but prevents us from contaminating the build container with things that are technically not necessary.

### systemd magic

The last option would be to use something like the systemd-nspawn user namespace stuff to run the build as a user controlled by systemd.  This has a hard dependency on systemd, obviously, but we already have that.  In some ways, this is the "cleanest" solution -- we don't ever have to manage the user directly ourselves again -- but also the most complicated from an implementation standpoint.  I'm not even 100% sure it's possible, though a read of the documentation seems to imply that it is.

Thoughts?

**Comment by ximion** [comment]
In the long run we will likely just want to create the user from the outside, or have systemd do it, in the short term just to make this work again, ensuring passwd is present is a good enough fix :-)
